import { useState, useEffect } from 'react';
import './Footer.css';

export default function Footer({ isReaderPage = false }) {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth <= 768);
    };
    
    // Check initially
    checkMobile();
    
    // Add resize listener
    window.addEventListener('resize', checkMobile);
    
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  // Hide footer on reader page in mobile view
  if (isMobile && isReaderPage) {
    return null;
  }

  return (
    <footer className="app-footer">
      <p>All text content is generated by AI</p>
    </footer>
  );
}
